### ISSUE TITLE
InvalidLinkBear does not detect all 40x series errors

### ISSUE THREAD

**Issue by Mixih** [coala/coala-bears#1155]
Currently it only does 404 and 410 errors. All 404-500 series error codes are errors.

**Comment by jayvdb** [comment]
No, not all 404-500 error codes are permanent errors.

**Comment by Mixih** [comment]
yeah mistake. Only 406, 405, and 408 were added

**Comment by jayvdb** [comment]
Actually, none of them are IMO 100% errors which should be called errors.  However they are often errors, and, since we allow URLs to be ignored, it is a good default to reject them.

405 (Method Not Allowed) and 406 (Not Acceptable) are content negotiation, based on the *server*'s logic, and a simple fetcher cant know whether there are other acceptable content requests which would be acceptable.

Specifically, 405 can occur if a link to non-GET is put into documentation, and this occurs in technical documentation.

406 is unlikely to occur with raw `urllib`, as I assume it doesnt set any `Accept*` headers in the request.  I dont recall whether `requests` sets any Accept headers by default.

408 is the most problematic here, as it can be the result of network problems between the client and host, and the 'host' is often immediately behind other equipment that is failing.  i.e. the routers are failing to handle increased load. And for 408 errors, the bear's ignore functionality isnt going to be very useful, as the problem was intermittent, unless the same website has regular intermittent problems.

Also CI failure due to intermittent problems like 408 are really hard to debug as the CI worker is usually using a different network path to the host server.

**Comment by Mixih** [comment]
Hmm, ok so we omit 408, and add severity mappings. Are the extra features worth the extra complexity that it brings?

**Comment by jayvdb** [comment]
What caused this issue to be raised?  Did someone have a link which was HTTP 405,6,8?

**Comment by Mixih** [comment]
yeah, in a test case. It seems like a few those might have been nice to add though on a second look they aren't really permanent link errors like this bear is supposed to detect.... So I guess this is a won't fix
