### ISSUE TITLE
PyFlakes bear dependency conflict in latest coala bears

### ISSUE THREAD

**Issue by Mixih** [coala/coala-bears#1228]
`[ERROR][17:33:55] There is a conflict in the version of a dependency you have installed and the requirements of coala. This may be resolved by creating a separate virtual environment for coala or running `pip install "pyflakes!=1.2.0,!=1.2.1,!=1.2.2,<1.4.0,>=0.8.1"`. Be aware that the latter solution might break other python packages that depend on the currently installed version.`

**Comment by jayvdb** [comment]
Copying https://github.com/coala/coala-bears/issues/1245#issuecomment-270047696 here:

> The uncontrollable part of the pyflakes problem was between autoflake(pyflakes) and radon(flake8).
autoflake pinned their pyflakes to 1.3, and we followed suite, which only temporarily solved our problem.  The real problem was radon, which depended on flake8 without any version spec, and different versions of flake8 have different pinned versions of pyflakes.

**Comment by jayvdb** [comment]
Note that using pyflakes 1.4 is quite important, specifically for an AST change in Python 3.6 ( https://github.com/PyCQA/pyflakes/pull/80 )
