### ISSUE TITLE
ShellCheckBear should have a CabalRequirement

### ISSUE THREAD

**Issue by jayvdb** [coala/coala-bears#1359]
CabalRequirement (and DistributionRequirement) was created recently. It should be used for ShellCheckBear.

**Comment by ankit01ojha** [comment]
@jayvdb Could you tell me how this can be done?

**Comment by jayvdb** [comment]
See https://gitlab.com/coala/package_manager/blob/master/dependency_management/requirements/CabalRequirement.py , and look for PipRequirement in the coala-bears repo for similar examples.

**Comment by sils** [comment]
Shouldn't we rather have like a distribution requirement which knows that as a backup it can use the cabalrequirement instead of requiring both? I think this handling is wrong and will lead to our package management trying to install the package twice.

Related issues: https://github.com/coala/coala-bears/issues/1358 and I think there's more issues like this one.

**Comment by jayvdb** [comment]
A DistributionRequirement cant know anything. The installer (cib) controlled by a real person chooses the type of installation.
The bear provides the metadata. How to structure it to describe 'or' is something cib needs to do , quickly.

**Comment by sils** [comment]
@jayvdb so shouldn't we implement the or before we start using it?

**Comment by jayvdb** [comment]
coala core would also be impacted. Raised https://github.com/coala/coala/issues/3713 about that.

**Comment by jayvdb** [comment]
Note Ubuntu xenial [ships 0.3.7](http://packages.ubuntu.com/search?suite=xenial&searchon=names&keywords=shellcheck)
