### ISSUE TITLE
Markdownbear isn't working as intended

### ISSUE THREAD

**Issue by RohanVB** [coala/coala-bears#1542]
https://github.com/coala/coala-atom/pull/47

The patch deletes the entire README file 

How to reproduce?:
Clone the coala-atom repo
Run `coala`

**Comment by meetmangukiya** [comment]
> The patch deletes the entire README file

This is critical :O

**Comment by meetmangukiya** [comment]
Seems like a duplicate https://github.com/coala/coala-bears/issues/1235

**Comment by jack17529** [comment]
@RohanVB  don't post duplicate bugs otherwise BIG developers gonna get mad at you :+1:

**Comment by RohanVB** [comment]
Sorry, couldn't find that issue. Thanks guys :D

**Comment by sils** [comment]
FWIW duplicate issues happen all the time, when in doubt rather post an issue than not posting it. Also those "big developers" usually don't get mad, we acknowledge that everyone including us has his or her flaws but the most important bit is improving ourselves and for that we need to be able to give each other honest feedback. We tell you if we think you can do something better and we hope that you tell us if we can do something better because otherwise we have a huge disadvantage of not being able to grow on this project.
