### ISSUE TITLE
Trigger new build automatically on master

### ISSUE THREAD

**Issue by sils** [coala/coala-bears#173]
it'd be neat if we could make a POST to `https://registry.hub.docker.com/u/coala/base/trigger/c020631d-8bec-44e1-8b2b-f4f69784139f/` on every master build so the `coala/base` image gets rebuilt automatically

**Comment by AbdealiJK** [comment]
I'm a little against this. Because stuff is going to happen to another repo based on this repo. (Repo dependency?)
Repos should be atomic units and should only interface with one another with package managers.

If we want to officially support it - I think we should just move that Dockerfile here and setup docker to build whenever we push to this repo (https://docs.docker.com/docker-hub/github/)

Seems cleaner and makes sense to me.
If you really really want the Dockerfile to be in it's own repo - then we could do a git submodule (although I dont like that very much)

**Comment by sils1297** [comment]
The docker repo pulls coala from pypi not from this repo.

**Comment by jayvdb** [comment]
We now have a 24 hr cron jobs on Travis project for the docker repo.
I think that is regular enough to catch problems quickly.
