### ISSUE TITLE
PHPCodeSnifferBear warns about too long lines independent of max_line_length

### ISSUE THREAD

**Issue by sils** [coala/coala-bears#1950]
I'm getting two kinds of errors after setting max_line_length to 10:

```
|    | Line exceeds 10 characters; contains 36 characters
```

as well as:

```
|    | Line exceeds maximum limit of 100 characters; contains 112 characters
```

what's the second thing? Seems untouched by our config.

CC @Asnelchristian because he basically wrote PHPCodeSnifferBear.

**Comment by bhavishyagopesh** [comment]
@sils I'm trying to debug this(but unable to reproduce this behaviour...) could you tell what did you run...like did you pass `-S max_line_length=10` or you passed some config-file. thanks

**Comment by sils** [comment]
most likely I used `-S` but it shouldn't matter. Weird thing is I'm getting two errors for the same line with different limits.

**Comment by bhavishyagopesh** [comment]
@sils So I found from where two errors are coming, the first is usual bear error but the second is coming from inside of phpcs(Actually phpcs has `LineLengthSniff.php` which classifies line having more than 80 chars as warning and >100 as error(that's why the second error)) -- [here](https://github.com/squizlabs/PHP_CodeSniffer/blob/master/src/Standards/Generic/Sniffs/Files/LineLengthSniff.php#L161)

But I still need to find how our bear is handling the response from phpcs...
