### ISSUE TITLE
Update the jshint version

### ISSUE THREAD

**Issue by newbazz** [coala/coala-bears#2216]
Update the jshint version to `2.9.5`.

**Comment by thealphadollar** [comment]
@newbazz I would like to begin my contribution by doing this. Can you please guide me a little on how to do it?

**Comment by newbazz** [comment]
just do `git grep jshint` and change the version in all the files ;P

**Comment by thealphadollar** [comment]
@newbazz  assign me.

**Comment by Makman2** [comment]
It seems that https://github.com/coala/coala-bears/pull/2197 implicitly needs to do this. Because this issue originated from that PR, I would rather merge the change in that PR than from this issue :)

@thealphadollar I hope you don't mind ;)

Closing as soon as https://github.com/coala/coala-bears/pull/2197 is merged.

**Comment by Makman2** [comment]
Other PR approved, closing.
