### ISSUE TITLE
GoVetBear throwing error on appveyor

### ISSUE THREAD

**Issue by MacBox7** [coala/coala-bears#2337]
GoVetBearTest failing with error `The local bear 'GoVetBear' yields a result although it shouldn't.`
Link: https://ci.appveyor.com/project/coala/coala-bears/build/1.0.9263/job/4xamw8qmesan9aat

**Comment by MacBox7** [comment]
Go vet seems to ignore some syntax error, to be more precise 
```
prog.go:6:2: too many arguments to return
	have (number)
	want ()
```
as in our case. The reason being the previous function was returning value and no return type was specified. And as per GoLang `main` function has no arguments and no return value. So, both `vet_good.go` and `vet_bad.go` were throwing syntax error.

I tested the built without cache and still they were failing previously and so not a problem with VM's cache.
Could be related to go/govet version change.

Travis and CircleCI were working fine since they have ubuntu environment whereas AppVeyor was failing as it has Windows environment. I observed this similar thing on my own local Ubuntu and  Windows system.The reason for inconsistency could be a bug in GoLang, but I am not sure.

**Comment by Makman2** [comment]
Does this one occur on master?

**Comment by virresh** [comment]
@MacBox7 
The error is apparently because two days ago appveyor upgraded from go 1.9 to go 1.10
and 1.10 bring some changes relevant to ```go vet```
So here are some possible things that we can do:

- Instead of go vet, we can use go tool vet
- We need to update dependencies and add ppa for go 1.10 for apt and accordingly change the tests as well
- We can adjust appveyor to use go110

**Comment by MacBox7** [comment]
@makman2 yes this is on master branch. Needs to be patched so that other builds don't fail.
