### ISSUE TITLE
Add new generic bear

### ISSUE THREAD

**Issue by kriti21** [coala/coala-bears#2358]
This generic bear should check for issues like:
1. Leaving blank line after class definition.
2. Whether the documentation is sufficient like for function it should check if parameters and the role of function in explained etc
3. Whether documentation is followed by a blank line
3. Whether variable names are good (self-explanatory)

Tags: bear-proposal, generic-bears

**Comment by RaiVaibhav** [comment]
>role of function in explained
We can check what it is return type and can verify it but how can a Bear check what the function is returning like ` :return: a dictionary of a settings with key as x any it value will be y ` , how are you you going to verify that what will be x and what will be y?

Any Idea If anyone take this issue how he/she will overcome this problem

**Comment by RaiVaibhav** [comment]
Suppose a function fetching some random values of list or a fetching some dictionary with random key and value , the how we can what will be the role of function

**Comment by Makman2** [comment]
> to check the configuration of files

which files? :)

**Comment by kriti21** [comment]
>which files? :)

By files I mean code written in any programming language. This bear would be able to solve issues like https://github.com/coala/coala-bears/issues/620 , https://github.com/coala/coala-bears/issues/1923 and https://github.com/coala/coala-bears/issues/1922 automatically. What do you think @Makman2 ?

**Comment by Makman2** [comment]
Could you maybe make the issue more precise by filing new issues for features that belong together? For example blank lines after class definition are somewhat different from detecting good variable names.

**Comment by jayvdb** [comment]
This was spawned from https://github.com/coala/coala-bears/issues/620 , but has too many unrelated checks in it, and not well understood yet.

There are linter bears (pycodestyle & pydocstyle)  which do most of what was requested in https://github.com/coala/coala-bears/issues/620 for Python.

And we have a generic bear which does docstrings for any language, so that might also be a path forward.  The non-docstring related stuff in this issue would need to be reconsidered, and would need to wait until we had AST in the bears.
