### ISSUE TITLE
German sample in LanguageToolBearTest isn't good german

### ISSUE THREAD

**Issue by sils** [coala/coala-bears#25]
_From @sils1297 on February 14, 2016 16:57_

A german newcomer will probably get that right easily :)

difficulty/newcomer
area/bears
type/test

_Copied from original issue: coala-analyzer/coala#1473_

**Comment by Adrianzatreanu** [comment]
why is this a type/test?

**Comment by AbdealiJK** [comment]
Because it's a sentence that needs to be changed in a test file

**Comment by Hazen91** [comment]
I can do it if you like

**Comment by Adrianzatreanu** [comment]
Hi! Welcome to our community and thank you for your interest!

I have sent you an invitation to join our community. This is needed so we can coordinate tasks with you and make sure no two persons are working on the same thing. If you can't find the mail, you should be able to join us at http://github.com/coala-analyzer/!

We'd love to be able to help you when problems occur. Just join us on [our gitter channel](https://coala.io/chat) and tell us about them :)

**Comment by daminisatya** [comment]
Hey @sils1297 Is this issue fixed ? Can i make my first contribution to coala here ?

**Comment by Cosmopal** [comment]
I can look at it

**Comment by jayvdb** [comment]
@Cosmopal, do you understand German? Do you know what it should be changed to?

**Comment by kerstin** [comment]
The English sample in that file doesn't look like correct English either. ;P

**Comment by Cosmopal** [comment]
At least I think I do @jayvdb , I know a bit of it. Enough to correct that out. As I see it is copied from google translate, which is generally not a good idea.

**Comment by kerstin** [comment]
Maybe the English sentence should get fixed first though. German native speaker here, btw.

**Comment by kerstin** [comment]
(I'd suggest removing "Jedermann" in any case as it's gendered language.)

**Comment by Cosmopal** [comment]
@kerstin ok, will do so tomorrow

**Comment by kerstin** [comment]
I've submitted a fix because I don't see this getting done anymore based on no or slow reactions by would-be Hacktoberfest contributors.

However, it would have been really helpful if the gitmate-bot message/your particular contributing rules had already been mentioned or linked to from the beginning (_especially_ for newcomers coming in through the Hacktoberfest tag)... I'm now being told to do x, y and z _after_ submitting, so uhh, I guess I have to redo my commit so it aligns 100% with your contribution rules?

–> If any of you above want to redo it based on my suggested changes, feel free.

**Comment by kerstin** [comment]
(But please check gitmate-bot's message in the linked PR first. #935)

**Comment by sils** [comment]
@kerstin we do have a lot of newcomer issues and it's very hard to maintain them. We try to avoid duplicate assignments by making sure people are assigned to the issues they work on.

The stuff GitMate tells you should ideally be linked from the newcomers guide as well, but it's a good idea to put this "checklist" in there as well. We should pick that up. Do you have any other suggestions on how we can improve the workflow? Trust me, we're all volunteers and nobody is interested in you or anyone else wasting your time.

**Comment by kerstin** [comment]
Hey @sils, it could very well be that how you do things works fine for regular contributions because for these, would-be fixers will be folks who are already familiar with the project (most likely), and they'll be browsing the issues after having had a look around.

With the Hacktoberfest tag though, people just go through GitHub search for the tag and might not even check out the entire project & all available guidelines. So I'm guessing it would have made sense to explicitely make people aware of them when you added the tag to issues. Too late for that now (: but maybe something to keep in mind for next time.

**Comment by kerstin** [comment]
I'll check back in in November and redo the commit so it follows the guidelines _if_ it hasn't been picked up by anyone else until then in any case. As said above: if anyone else wants to do the PR until then to fill their Hacktoberfest quota to get a shirt from DigitalOcean, I'm happy to let them reuse my suggested changes. ^^
