### ISSUE TITLE
Remove `package-lock.json` from gitignore

### ISSUE THREAD

**Issue by Makman2** [coala/coala-bears#2508]
npm clearly states that this file should be commited. From `npm help package-lock.json`:

> package-lock.json is automatically generated for any operations where npm modifies either the node_modules tree, or package.json. It describes the exact tree that was generated, such that subsequent installs are able to generate identical trees, regardless of intermediate dependency updates.
>
> This file is intended to be committed into source repositories, and serves various purposes:
>
> - Describe a single representation of a dependency tree such that teammates, deployments, and continuous integration are guaranteed to install exactly the same dependencies.
> - Provide a facility for users to "time-travel" to previous states of node_modules without having to commit the directory itself.
> - To facilitate greater visibility of tree changes through readable source control diffs.
> - And optimize the installation process by allowing npm to skip repeated metadata resolutions for previously-installed packages.
>
> One key detail about package-lock.json is that it cannot be published, and it will be ignored if found in any place other than the toplevel package. It shares a format with npm-shrinkwrap.json(5), which is essentially the same file, but allows publication. This is not recommended unless deploying a CLI tool or otherwise using the publication process for producing production packages.
>
> If both package-lock.json and npm-shrinkwrap.json are present in the root of a package, package-lock.json will be completely ignored.

This issue is about reverting the change in https://github.com/coala/coala-bears/pull/2494 again.

**Comment by KaplanAlex** [comment]
Can I be assigned this issue?

**Comment by jayvdb** [comment]
Those reasons have little relevance to this repository, as we do not use node_modules to build our product, and our package.json has no impact on the versions that our users would install.

If you want to have a lock file, please also add CI which ensures it is updated sensibly, and has readible diffs.  You will quickly find that then you need to control the npm version people use, otherwise the lock file will change with every commit because devs use different npm versions.  It is a nightmare.  Use `pnpm` for sanity.
