### ISSUE TITLE
CheckstyleBear offset bug

### ISSUE THREAD

**Issue by jayvdb** [coala/coala-bears#2563]
https://ci.appveyor.com/project/jayvdb/coala-bears/build/job/xhu5jueyyennp1u3#L1618

**Comment by li-boxuan** [comment]
First, line number starts at 1.

Sometimes we can see messages like `CheckstyleBad.java:0: Missing package-info.java file`. 

`This is because some checks print violations their own way, especially when they don't use the java parser`
https://github.com/checkstyle/checkstyle/blob/master/src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocPackageCheck.java#L89

Second, column number starts at 0. But they have an issue to change it to 1. https://github.com/checkstyle/checkstyle/issues/4997

To see the whole context https://gitter.im/checkstyle/checkstyle?at=5b3cc52933b0282df4ff75e3
