### ISSUE TITLE
Add settings for EslintBear

### ISSUE THREAD

**Issue by anctartica** [coala/coala-bears#2635]
Add language setting to EslintBear to support using various parsers and plugins available for the linter.

**Comment by jayvdb** [comment]
See also https://github.com/coala/coala-bears/issues/374 , and other "eslint" and "eslintbear" issues.

Also JSHintBear has a lot more settings and we should be trying to use similar setting names for the JS bears where the setting has the same effect.  We can rename JSHintBear settings if a better name is required in order to be suitable for both bears. (setting name deprecation is an easy decorator)
