### ISSUE TITLE
GitRevertInspectBear: make asciinema

### ISSUE THREAD

**Issue by sangamcse** [coala/coala-bears#2738]

**Comment by sangamcse** [comment]
@KVGarg, this issue is reserved for GCI participants.

**Comment by KVGarg** [comment]
Ok

**Comment by bnu123** [comment]
@sangamcse It doesn't show any label specifying GCI

**Comment by sangamcse** [comment]
Hey @KVGarg and @bnu123, this issue is not added in GCI task yet so it is open for all. Sorry for https://github.com/coala/coala-bears/issues/2738#issuecomment-435594142

**Comment by KVGarg** [comment]
Ask on gitter chat to get this issue assigned to you. 👍

**Comment by bnu123** [comment]
@sangamcse Hi, due to exams, I was inactive, but now I am available. Can you guide me what actually I have to do in this issue. I created a file and then made a commit to that file, then I reverted the commit and used coala as `coala --files=Spam.txt --beard=GitRevertInspectBear --save`, and coala ran successfully, so I don't know what I've to do? do I need to make a bad revert, if yes then how ? Please help.
