### ISSUE TITLE
moban job is red

### ISSUE THREAD

**Issue by jayvdb** [coala/coala-bears#2853]
A sync is required (see readme in https://gitlab.com/coala/mobans), but some of the moban differences will require more work.

**Comment by jayvdb** [comment]
See https://travis-ci.org/coala/coala-bears/builds/488356492

This job is allowed to fail on PRs on the coala & coala-bears repos only, but is a failure on master for these two repos.  The rationale for that is PR authors may be unprepared to tackle moban failures, especially in these two rather complicated repos.

The failure on master ensures that the developers & maintainers still notice the problems, and fix them within a reasonable period of time.

Another benefit, it allows us to be lazy, and have these two repos be slightly ahead of the templates , simplifying CI changes a bit.  But this isnt a good reason, as it means anyone trying to fix the moban job (i.e. you) need to *guess* whether the repo or the template is authoritative.  Use `git log` to check dates of any changes in local repo vs the template to help guess which is the more correct.

If you look at the recent commits to coala and mobans repos, you will see I did a sync to coala repo of most changes, and then a sync back to mobans repo of some changes where the coala repo had the better version.

**Comment by frextrite** [comment]
Digging up on moban atm. But I got a few queries,

> This job is allowed to fail on PRs on the coala & coala-bears repos only, but is a failure on master for these two repos.

This job *may* fail on PRs and *may* fail on master(if a PR merge breaks the template) but technically *must never* fail on master. Though currently it is failing and that needs to be fixed.

> The failure on master ensures that the developers & maintainers still notice the problems, and fix them within a reasonable period of time.

If moban fails, do a sync else :tada: right?

> it allows us to be lazy

Developers and users generally are. No doubt here.

> A sync is required

Currently `git diff --exit-code` returns a non-zero code. So dependencies and structure needs to be fixed so that `git diff --exit-code` exits gracefully, right?

**Comment by ayan-b** [comment]
@frextrite , It seems a sync is required. You may want to check https://gitlab.com/coala/mobans .
