### ISSUE TITLE
PySafetyBear broken by new release: TypeError: check() missing 1 required positional argument: 'proxy'

### ISSUE THREAD

**Issue by jayvdb** [coala/coala-bears#2857]
https://travis-ci.org/jayvdb/coala-bears/jobs/488802415

```py
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/coalib/bears/Bear.py", line 454, in execute
    return [] if result is None else list(result)
  File "/home/travis/build/jayvdb/coala-bears/bears/python/requirements/PySafetyBear.py", line 97, in run
    ignore_ids=cve_ignore):
TypeError: check() missing 1 required positional argument: 'proxy'
```

**Comment by Naveenaidu** [comment]
@jayvdb 
The above error occurs due to the recent change in the `Safety` package which has been release on [5th Feb](https://pypi.org/project/safety/#history) (Today). The new version comes with the added functionality to support proxies which the `Requests` module of python uses.

The commit which made these changes is [here](https://github.com/pyupio/safety/pull/181/files)

In order to fix the above Travis error we would now have to pass an additional argument called as proxy in the PySafetyBear at the [line](https://github.com/coala/coala-bears/blob/master/bears/python/requirements/PySafetyBear.py#L97). The new safety.check() function should look like:
```
proxy = {}
 for vulnerability in safety.check(packages, key=None,
                                          db_mirror=db_path, cached=False,
                                          ignore_ids=cve_ignore,proxy=proxy):
if 'cve' in vulnerability.vuln_id.strip().lower(): 
```
The argument proxy is a `dictionary` datatype which holds values something like:
```
proxies = {
  "http": "10.10.1.10:3128",
  "https": "10.10.1.10:1080",
}
```
The reference for the above thing is taken from [StackOverflow](htuest tps://stackoverflow.com/questions/8287628/proxies-with-python-requests-module) and [Requests Docs](http://docs.python-requests.org/en/latest/user/advanced/#proxies)

The tests for the above new argument can be found at (test_safety)[https://github.com/pyupio/safety/blob/0879d6f83bd69c58cc7115098f91e01a15b7bfb0/tests/test_safety.py#L150] of the Safety library.

**Comment by jayvdb** [comment]
> Since we don't use any proxies, I guess we can leave it as a empty dictionary like proxy = {}

Yup, that is what we should do.

It might also be possible to set `proxy=None`, and that would be preferred way to indicate no proxy are requested.
