### ISSUE TITLE
lxml 4.4.0 dropped support for Python 3.4

### ISSUE THREAD

**Issue by abhishalya** [coala/coala-bears#2940]
Need to cap below 4.4.0.

**Comment by jayvdb** [comment]
This should be done like https://github.com/moremoban/moban/commit/5e895b6a9e3a7b06c3cbd3ea651b197990366c33 , so that newer versions of Python are not effected.

Also the lxml dependency is special, and is managed in the .ci/deps.python-packages.ps1 for Windows so that it is installed with special flags.  That fix needs to be done in mobans repo, as lxml is important in all repos.

**Comment by jayvdb** [comment]
Where is this breaking a build ?

**Comment by abhishalya** [comment]
I saw it [here](https://travis-ci.org/coala/coala-bears/jobs/564987641#L892). Now it seems we have even more build failures.

**Comment by jayvdb** [comment]
Also triggered at https://github.com/coala/coala/pull/6054 . Annoying.

**Comment by jayvdb** [comment]
Temporary solution in https://gitlab.com/coala/mobans/merge_requests/135 , deploying to coala and coala-quickstart.

**Comment by jayvdb** [comment]
Cherry-picked https://github.com/abhishalya/coala-bears/commit/bf3b7a2ef692b0cc3665650fbb20072fd2870c79 onto https://github.com/coala/coala-bears/pull/2942 .  Note I needed to also update the pin in `bear-requirements.txt` and adjusted the commit message a little .

Feel free to create a PR with it and ill rebase on top of your PR.  Otherwise, your commit will show it was amended by me.  Up to you

**Comment by jayvdb** [comment]
The reason it was needed, despite the pre-install, is that tox on Unix is not using 'site-packages' so versions installed outside the tox venv are not visible inside, so tox tries to use an old pip to install lxml, and fails.
https://travis-ci.org/jayvdb/coala-bears/jobs/567832173

> This should be done like moremoban/moban@5e895b6 , so that newer versions of Python are not effected.

The minreqs templates should be implemented in all our repos, and will very likely reveal that our minimum versions are wrong.

The new travis templates do support this, but we should start with the gitlab-ci templates for the gitlab repos, as their minimums effect coala core and coala bears.

> Also the lxml dependency is special, and is managed in the .ci/deps.python-packages.ps1 for Windows so that it is installed with special flags. That fix needs to be done in mobans repo, as lxml is important in all repos.

No change is necessary in mobans, as the currently logic in .ci/deps.python-packages.ps1 uses the latest pip and --prefer-binary picks the latest binary version for py34, which happens to be the older version because none are built for py34.

**Comment by jayvdb** [comment]
We currently dont have support for dependencies for per-Python-version ('constraints'), and I suspect that is going to take a while, so we can revisit this problem whenever we find that <4.4.0 is causing some other bug.

**Comment by abhishalya** [comment]
>Cherry-picked abhishalya@bf3b7a2 onto #2942 . Note I needed to also update the pin in bear-requirements.txt and adjusted the commit message a little .

No problem :+1:
