### ISSUE TITLE
Update files to reflect name change (from `coala-analyzer` to `coala`)

### ISSUE THREAD

**Issue by Dawny33** [coala/coala-bears#840]

**Comment by divyam3897** [comment]
Hi, I want to fix it. I need to change all the "coala-analyzer" strings with "coala" in Readme.rst?

**Comment by sils1297** [comment]
@divyam3897 apparently @Dawny33 is already working on this

**Comment by Srijancse** [comment]
Can I fix this? Is this opened, yet?

**Comment by sils1297** [comment]
@Dawny33 is working on this

**Comment by Adrianzatreanu** [comment]
unassigned due to inactivity

**Comment by OctavianGuzu** [comment]
Assign me this please!

**Comment by sils** [comment]
Hey @OctavianGuzu ,

We recommend to not do newcomer issues anymore because they take us more time to file than to fix them - let other newcomers can have a few as well. The next level for you are the [low difficulty issues](http://tinyurl.com/coala-low) - you can now dive into whatever you want. Let us know if you need help or have any special interests - there's a lot of stuff going on and usually interests can be met :)

Cheers!

**Comment by arsalansaad** [comment]
can i work on this?

**Comment by SanketDG** [comment]
unassigned due to unactivity

**Comment by insanicly** [comment]
Hi, if I understand this issue correctly, we wanted all coala-analyzer words to the coala in documentations. 

But it seems that for example:

DESCRIPTION.rst

there is a link "http://coala-analyzer.org" and when I change it to "http://coala.org" it redirects into wrong page. I can correct this link as "http://coala.io" or something else but I can't decide if it is wrong or something unnecessary.

Can we make the description of this issue more clear?

**Comment by RaiVaibhav** [comment]
@insanicly  are you still working on this

**Comment by insanicly** [comment]
hi @RaiVaibhav, no not working since the issue has no description and no answer to my question above.

**Comment by jayvdb** [comment]
There are no mentions of `coala-analyzer` anywhere in this repository.
https://github.com/coala/coala-bears/search?utf8=%E2%9C%93&q=coala+analyzer&type=
