### ISSUE TITLE
PEP8Bear: Make asciinema. 

### ISSUE THREAD

**Issue by Udayan12167** [coala/coala-bears#873]

**Comment by Niket100** [comment]
assign me this

**Comment by sarthak268** [comment]
please assign me this

**Comment by depuk98** [comment]
assign me this

**Comment by Adrianzatreanu** [comment]
unassigning due to inactivity

**Comment by SarthakNijhawan** [comment]
@Adrianzatreanu , assign me this

**Comment by jayvdb** [comment]
Can we leave these asciinema tasks for the [GCI](https://github.com/coala/coala/wiki/Google-Code-In) participants, please?

**Comment by AnaDenisa** [comment]
Hello! Please assign me to this :)

**Comment by SanketDG** [comment]
unassigned due to inactivity

**Comment by mubaris** [comment]
I will do this :smile:

**Comment by Ciemaar** [comment]
What is the problem here?

**Comment by SanketDG** [comment]
The task is to record an asciinema that demonstrates the use of PEP8Bear

**Comment by SanketDG** [comment]
The task is to record an asciinema that demonstrates the use of PEP8Bear

**Comment by pavankoushik22** [comment]
can you guys assign this to me?

**Comment by kriti21** [comment]
Please assign this issue to me.

**Comment by MacBox7** [comment]
Can this be assigned to me ?

**Comment by MacBox7** [comment]
Is there some problem with the implementation? Because the bear doesn't fix all issues in one go. I have to run it multiple times on the same file to patch all the inconsistency.

Tested on the following code:
`# Import should be separated by end of line
import sys, math

# Multiple statements in one line is not allowed
for i in range(10): print "foo"; print "bar"

# comparison to None should be 'if cond is None
if object == None: pass
`
Expected output: 
`# Import should be separated by end of line
import sys
import math

# Multiple statements in one line is not allowed
for i in range(10):
    print "foo"
    print "bar"

# comparison to None should be 'if cond is None
if object is None:
    pass
`

Actual output: 
`# Import should be separated by end of line
import sys
import math

# Multiple statements in one line is not allowed
for i in range(10): print "foo"; print "bar"

# comparison to None should be 'if cond is None
if object == None: pass
`

**Comment by Makman2** [comment]
Is this related to the issue?

**Comment by Makman2** [comment]
It shouldn't be necessary to run coala multiple times (we aren't LaTeX 😅 ), so yeah this is something I would consider a bug --> separate issue.

**Comment by MacBox7** [comment]
Figured it out, to patch all changes in one go had to use --apply-patches
